# -*- coding: utf-8 -*-
"""student_risk_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbezlCm6GTYLXujPV97dnS7eydPyr_j8
"""

import os
if not os.path.exists('student_performance_dataset.csv'):
  print('Error: student_performance_dataset.csv not found.')
else:
  !file student_performance_dataset.csv

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Load dataset automatically
try:
    data = pd.read_excel("student_performance_dataset.csv")
except:
    data = pd.read_csv("student_performance_dataset.csv", encoding="latin1")

# Clean column names
data.columns = data.columns.astype(str).str.strip().str.lower()

print("Columns:", data.columns.tolist())

# Input features
X = data[[
    "study_hrs",
    "attendance",
    "previous_mark",
    "assignment_score"
]]

# Target
y = data["result"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create and train model
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# Test model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Student Performance Risk Classification")
print("Model Accuracy:", round(accuracy * 100, 2), "%")

# Example student
student = pd.DataFrame(
    [[3, 65, 55, 60]],
    columns=[
        "study_hrs",
        "attendance",
        "previous_mark",
        "assignment_score"
    ]
)

prediction = model.predict(student)

print("Example Student Prediction:", prediction[0])

print(data.columns.tolist())